import{a as b,i as d,S as m}from"./assets/vendor-BDaiwwc1.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const v="https://pixabay.com/api/",L="41633304-c06bc91ac11626a6cec46e525";async function h(s="",t){const i=await b.get(`${v}`,{params:{key:L,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}});return console.log(i.data),i.data}function g(s){return s.length?s.map(({webformatURL:t,largeImageURL:i,tags:a,likes:e,views:r,comments:n,downloads:p})=>`<li class = "gallery-item"><a class = "gallery-link" href = "${i}"><img class = "gallery-image" src=${t} alt="${a}"></a>
            <div class="social-activity">
            <ul class="social-activity-list">
            <li class="social-activity-list-item">Likes <span class="number">${e}</span></li>
            <li class="social-activity-list-item">Views <span class="number"> ${r}</span></li>
            <li class="social-activity-list-item">Comments <span class="number"> ${n}</span></li>
            <li class="social-activity-list-item">Downloads <span class="number">${p}</span></li>
            </ul>
            </div>
          </li>`).join(""):(d.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"bottomRight"}),"")}const f=document.querySelector(".form"),o=document.querySelector(".js-list");document.querySelector(".form button");const u=document.querySelector(".load");let l,c=1,y;f.addEventListener("submit",w);u.addEventListener("click",M);async function w(s){if(u.classList.remove("visible"),s.preventDefault(),c=1,l=s.target.elements.search.value,!!l){o.innerHTML='<div class="loader"></div></h1>';try{const t=await h(l,c);o.innerHTML=g(t.hits),u.classList.add("visible"),S()}catch(t){console.log(t),o.innerHTML="<h1>Something went wrong. Please try again.</h1>"}f.reset()}}function S(){y=new m(".gallery-item a")}o.addEventListener("click",s=>{s.preventDefault();const t=s.target;if(!t.tagName==="IMG"||s.currentTarget===t)return;new m(".gallery-item a").refresh()});async function M(){if(!l)return;if(c++,u.classList.remove("visible"),c>Math.ceil(500/15)){d.show({message:"We're sorry, but you've reached the end of search results.",position:"bottomRight"});return}o.insertAdjacentHTML("afterend",'<div class="loader"></div>');const s=document.querySelector(".loader"),t=document.querySelector(".gallery-item");try{const i=await h(l,c);o.insertAdjacentHTML("beforeend",g(i.hits)),u.classList.add("visible"),s.remove();const a=t.getBoundingClientRect().height;window.scrollBy({top:2*a,left:0,behavior:"smooth"}),y.refresh()}catch(i){console.log(i),o.innerHTML="<h1>Something went wrong. Please try again.</h1>"}}
//# sourceMappingURL=index.js.map
