import{a as v,i as m,S as d}from"./assets/vendor-BDaiwwc1.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function i(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=i(t);fetch(t.href,r)}})();const L="https://pixabay.com/api/",w="41633304-c06bc91ac11626a6cec46e525";async function h(s="",e){return(await v.get(`${L}`,{params:{key:w,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e}})).data}function g(s){return s.length?s.map(({webformatURL:e,largeImageURL:i,tags:a,likes:t,views:r,comments:c,downloads:b})=>`<li class = "gallery-item"><a class = "gallery-link" href = "${i}"><img class = "gallery-image" src=${e} alt="${a}"></a>
            <div class="social-activity">
            <ul class="social-activity-list">
            <li class="social-activity-list-item">Likes <span class="number">${t}</span></li>
            <li class="social-activity-list-item">Views <span class="number"> ${r}</span></li>
            <li class="social-activity-list-item">Comments <span class="number"> ${c}</span></li>
            <li class="social-activity-list-item">Downloads <span class="number">${b}</span></li>
            </ul>
            </div>
          </li>`).join(""):(m.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"bottomRight"}),"")}const f=document.querySelector(".form"),o=document.querySelector(".js-list");document.querySelector(".form button");const l=document.querySelector(".load");let u,n=1,y;f.addEventListener("submit",S);l.addEventListener("click",P);async function S(s){if(l.classList.remove("visible"),s.preventDefault(),u=s.target.elements.search.value.trim(),!!u){n=1,o.innerHTML='<div class="loader"></div></h1>';try{const e=await h(u,n);o.innerHTML=g(e.hits),l.classList.add("visible"),p(e.totalHits),M()}catch(e){m.error({message:`Error: ${e.message}`,position:"bottomRight"}),o.innerHTML="<h1>Something went wrong. Please try again.</h1>"}f.reset()}}function M(){y=new d(".gallery-item a")}o.addEventListener("click",s=>{s.preventDefault();const e=s.target;if(!e.tagName==="IMG"||s.currentTarget===e)return;new d(".gallery-item a").refresh()});async function P(){if(!u)return;if(n++,l.classList.remove("visible"),n>Math.ceil(500/15)){m.show({message:"We're sorry, but you've reached the end of search results.",position:"bottomRight"});return}o.insertAdjacentHTML("afterend",'<div class="loader"></div>');const s=document.querySelector(".loader"),e=document.querySelector(".gallery-item");try{const i=await h(u,n);o.insertAdjacentHTML("beforeend",g(i.hits)),l.classList.add("visible"),s.remove();const a=e.getBoundingClientRect().height;window.scrollBy({top:2*a,left:0,behavior:"smooth"}),y.refresh(),p(i.totalHits)}catch(i){m.error({message:`Error: ${i.message}`,position:"bottomRight"}),o.innerHTML="<h1>Something went wrong. Please try again.</h1>"}}function p(s){const e=Math.ceil(s/15);n>=e&&(l.classList.remove("visible"),m.show({message:"We're sorry, but you've reached the end of search results.",position:"bottomRight"}))}
//# sourceMappingURL=index.js.map
